name: 'Chat GPT Auto Review'
description: 'Save time with chatgpt'
inputs:
  GH_TOKEN:
    description: 'GitHub Token'
    required: true
  OPEN_API_KEY:
    description: 'OpenAI API Key'
    required: true
  DELIM:
    description: 'Delimiter'
    required: true
  PR_NUMBER:
    description: 'The PR number to append the review to'
    required: true
  REPO:
    description: 'The repo to append the review to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'